version: "3.4"

services:
  crypto-publisher:
    image: ghcr.io/devinrsmith/crypto-publisher:latest
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g
      DEEPHAVEN_BOOTSTRAP_SERVERS: redpanda:9092
      DEEPHAVEN_SCHEMA_REGISTRY_URL: http://redpanda:8081
    depends_on:
      - redpanda
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4500M
        reservations:
          memory: 1000M

  grpc-api:
    image: ghcr.io/deephaven-examples/grpc-api-crypto-application:latest
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/app.d
      DEEPHAVEN_BOOTSTRAP_SERVERS: redpanda:9092
      DEEPHAVEN_SCHEMA_REGISTRY_URL: http://redpanda:8081
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4500M
        reservations:
          memory: 1000M
    depends_on:
      - redpanda
    volumes:
      - data:/data
      - cache:/cache

  web:
    image: ghcr.io/deephaven-examples/web-crypto-application:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    volumes:
      - web-tmp:/tmp

  redpanda:
    image: ghcr.io/deephaven-examples/redpanda-crypto-application:latest
    volumes:
      - redpanda:/var/lib/redpanda/data

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:0.5.1
    environment:
      - BACKEND_ADDR=grpc-api:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - grpc-api

  envoy:
    image: ghcr.io/deephaven/envoy:0.5.1
    ports:
      - "10042:10000"

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - web
      - grpc-proxy
      - grpc-api

  client:
    image: ghcr.io/devinrsmith/crypto-client:latest
    environment:
      DEEPHAVEN_GRPC_API: grpc-api:8080
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    depends_on:
      - grpc-api
    profiles:
      - donotstart

volumes:
  redpanda:
  data:
  web-tmp:
  cache: